pub const TBOW_ACC_CAP: i32 = 140;

pub const TBOW_DMG_CAP: i32 = 250;

pub const MAGIC_DEF_EXCEPTIONS: [&str; 4] = [
    "Baboon Brawler (Level 56)",
    "Baboon Brawler (Level 68)",
    "Fragment of Seren",
    "Rabbit",
];

pub const TOA_MONSTERS: [&str; 32] = [
    "Akkha",
    "Akkha's Shadow",
    "Ba-Ba",
    "Baboon",
    "Baboon Brawler (Level 56)",
    "Baboon Brawler (Level 68)",
    "Baboon Mage (Level 56)",
    "Baboon Mage (Level 68)",
    "Baboon Shaman",
    "Baboon Thrall",
    "Baboon Thrower (Level 56)",
    "Baboon Thrower (Level 68)",
    "Cursed Baboon",
    "Volatile Baboon",
    "Kephri (Shield down)",
    "Kephri (Shield up)",
    "Agile Scarab",
    "Arcane Scarab",
    "Scarab Swarm",
    "Soldier Scarab",
    "Spitting Scarab",
    "Scarab",
    "Zebak",
    "Crocodile (Tombs of Amascut)",
    "Obelisk",
    "Tumeken's Warden (P2)",
    "Tumeken's Warden (P3)",
    "Tumeken's Warden (P4)",
    "Elidinis' Warden (P2)",
    "Elidinis' Warden (P3)",
    "Elidinis' Warden (P4)",
    "Core (Wardens)",
];

pub const TOA_PATH_MONSTERS: [&str; 9] = [
    "Akkha",
    "Akkha's Shadow",
    "Ba-Ba",
    "Kephri (Shield down)",
    "Kephri (Shield up)",
    "Arcane Scarab",
    "Spitting Scarab",
    "Soldier Scarab",
    "Zebak",
];

pub const WILDERNESS_MONSTERS: [&str; 38] = [
    "Artio",
    "Callisto",
    "Spindel",
    "Venenatis",
    "Calvar'ion (Normal)",
    "Calvar'ion (Enraged)",
    "Vet'ion",
    "Chaos Elemental",
    "Chaos Fanatic",
    "Crazy archaeologist",
    "Dark warrior",
    "Elder Chaos druid",
    "Ent",
    "Greater Skeleton Hellhound (Calvar'ion)",
    "Greater Skeleton Hellhound (Vet'ion)",
    "King Black Dragon",
    "Lava dragon",
    "Mammoth",
    "Revenant cyclops",
    "Revenant dark beast",
    "Revenant demon",
    "Revenant dragon",
    "Revenant goblin",
    "Revenant hellhound",
    "Revenant hobgoblin",
    "Revenant imp",
    "Revenant knight",
    "Revenant maledictus",
    "Revenant ork",
    "Revenant pyrefiend",
    "Runite Golem",
    "Scorpia",
    "Scorpia's guardian",
    "Scorpia's offspring",
    "Skeleton Hellhound (Calvar'ion)",
    "Skeleton Hellhound (Vet'ion)",
    "Spindel's Spiderling",
    "Venenatis' Spiderling",
];
