#[derive(Debug, Default, PartialEq)]
pub enum Prayer {
    #[default]
    None,
    ClarityOfThought,
    ImprovedReflexes,
    IncredibleReflexes,
    Chivalry,
    Piety,
    BurstOfStrength,
    SuperhumanStrength,
    UltimateStrength,
    ThickSkin,
    RockSkin,
    SteelSkin,
    SharpEye,
    HawkEye,
    EagleEye,
    Rigour,
    MysticWill,
    MysticLore,
    MysticMight,
    Augury,
}

#[derive(Debug, Default, PartialEq)]
pub struct PrayerBoost {
    pub prayer_type: Prayer,
    pub attack: u32,
    pub strength: u32,
    pub defence: u32,
    pub ranged_att: u32,
    pub ranged_str: u32,
    pub magic_att: u32,
    pub magic_str: u32,
}

impl PrayerBoost {
    pub fn new(prayer: Prayer) -> Self {
        match prayer {
            Prayer::ClarityOfThought => PrayerBoost {
                prayer_type: prayer,
                attack: 5,
                strength: 0,
                defence: 0,
                ranged_att: 0,
                ranged_str: 0,
                magic_att: 0,
                magic_str: 0,
            },
            Prayer::ImprovedReflexes => PrayerBoost {
                prayer_type: prayer,
                attack: 10,
                strength: 0,
                defence: 0,
                ranged_att: 0,
                ranged_str: 0,
                magic_att: 0,
                magic_str: 0,
            },
            Prayer::IncredibleReflexes => PrayerBoost {
                prayer_type: prayer,
                attack: 15,
                strength: 0,
                defence: 0,
                ranged_att: 0,
                ranged_str: 0,
                magic_att: 0,
                magic_str: 0,
            },
            Prayer::Chivalry => PrayerBoost {
                prayer_type: prayer,
                attack: 15,
                strength: 18,
                defence: 20,
                ranged_att: 0,
                ranged_str: 0,
                magic_att: 0,
                magic_str: 0,
            },
            Prayer::Piety => PrayerBoost {
                prayer_type: prayer,
                attack: 20,
                strength: 23,
                defence: 25,
                ranged_att: 0,
                ranged_str: 0,
                magic_att: 0,
                magic_str: 0,
            },
            Prayer::BurstOfStrength => PrayerBoost {
                prayer_type: prayer,
                attack: 0,
                strength: 5,
                defence: 0,
                ranged_att: 0,
                ranged_str: 0,
                magic_att: 0,
                magic_str: 0,
            },
            Prayer::SuperhumanStrength => PrayerBoost {
                prayer_type: prayer,
                attack: 0,
                strength: 10,
                defence: 0,
                ranged_att: 0,
                ranged_str: 0,
                magic_att: 0,
                magic_str: 0,
            },
            Prayer::UltimateStrength => PrayerBoost {
                prayer_type: prayer,
                attack: 0,
                strength: 15,
                defence: 0,
                ranged_att: 0,
                ranged_str: 0,
                magic_att: 0,
                magic_str: 0,
            },
            Prayer::ThickSkin => PrayerBoost {
                prayer_type: prayer,
                attack: 0,
                strength: 0,
                defence: 5,
                ranged_att: 0,
                ranged_str: 0,
                magic_att: 0,
                magic_str: 0,
            },
            Prayer::RockSkin => PrayerBoost {
                prayer_type: prayer,
                attack: 0,
                strength: 0,
                defence: 10,
                ranged_att: 0,
                ranged_str: 0,
                magic_att: 0,
                magic_str: 0,
            },
            Prayer::SteelSkin => PrayerBoost {
                prayer_type: prayer,
                attack: 0,
                strength: 0,
                defence: 15,
                ranged_att: 0,
                ranged_str: 0,
                magic_att: 0,
                magic_str: 0,
            },
            Prayer::SharpEye => PrayerBoost {
                prayer_type: prayer,
                attack: 0,
                strength: 0,
                defence: 0,
                ranged_att: 5,
                ranged_str: 5,
                magic_att: 0,
                magic_str: 0,
            },
            Prayer::HawkEye => PrayerBoost {
                prayer_type: prayer,
                attack: 0,
                strength: 0,
                defence: 0,
                ranged_att: 10,
                ranged_str: 10,
                magic_att: 0,
                magic_str: 0,
            },
            Prayer::EagleEye => PrayerBoost {
                prayer_type: prayer,
                attack: 0,
                strength: 0,
                defence: 0,
                ranged_att: 15,
                ranged_str: 15,
                magic_att: 0,
                magic_str: 0,
            },
            Prayer::Rigour => PrayerBoost {
                prayer_type: prayer,
                attack: 0,
                strength: 0,
                defence: 25,
                ranged_att: 20,
                ranged_str: 23,
                magic_att: 0,
                magic_str: 0,
            },
            Prayer::MysticWill => PrayerBoost {
                prayer_type: prayer,
                attack: 0,
                strength: 0,
                defence: 0,
                ranged_att: 0,
                ranged_str: 0,
                magic_att: 5,
                magic_str: 0,
            },
            Prayer::MysticLore => PrayerBoost {
                prayer_type: prayer,
                attack: 0,
                strength: 0,
                defence: 0,
                ranged_att: 0,
                ranged_str: 0,
                magic_att: 10,
                magic_str: 1,
            },
            Prayer::MysticMight => PrayerBoost {
                prayer_type: prayer,
                attack: 0,
                strength: 0,
                defence: 0,
                ranged_att: 0,
                ranged_str: 0,
                magic_att: 15,
                magic_str: 2,
            },
            Prayer::Augury => PrayerBoost {
                prayer_type: prayer,
                attack: 0,
                strength: 0,
                defence: 25,
                ranged_att: 0,
                ranged_str: 0,
                magic_att: 25,
                magic_str: 4,
            },
            _ => PrayerBoost {
                prayer_type: prayer,
                attack: 0,
                strength: 0,
                defence: 0,
                ranged_att: 0,
                ranged_str: 0,
                magic_att: 0,
                magic_str: 0,
            },
        }
    }
}
